config: fix meson build failure on ThunderX2
Since gcc-8.3(I tried 8.3 and 9.1), the meson build failed on ThunderX2.
It got the following compiling errors:
/usr/lib/gcc/aarch64-linux-gnu/9/include/arm_neon.h:26493:1: error:
inlining failed in call to always_inline ‘vmull_p64’: target specific
option mismatch 26493 | vmull_p64 (poly64_t a, poly64_t b)

Fixes: 7286c9d7234f ("config: add thunderx2 machine")
Cc: jerinj@marvell.com
Cc: stable@dpdk.org

Signed-off-by: Gavin Hu <gavin.hu@arm.com>
Reviewed-by: Phil Yang <phil.yang@arm.com>
Reviewed-by: Jingzhao Ni <jingzhao.ni@arm.com>
Signed-off-by: 0-day Robot <robot@bytheb.org>