mempool/octeontx2: fix compile issue
Change the definition of C99 style to C90 style.
compile log as below:

otx2_mempool_ops.c: In function ‘otx2_npa_populate’:
/dpdk/drivers/mempool/octeontx2/otx2_mempool_ops.c:790:2: error: \
	‘for’ loop initial declarations are only allowed in C99 mode
  for (int i = 0; i < OTX2_L1D_NB_SETS; i++)
  ^
/dpdk/drivers/mempool/octeontx2/otx2_mempool_ops.c:790:2: \
	note: use option -std=c99 or -std=gnu99 to compile your code
/dpdk/drivers/mempool/octeontx2/otx2_mempool_ops.c: At top level:
cc1: error: unrecognized command line option \
	"-Wno-address-of-packed-member" [-Werror]
cc1: all warnings being treated as errors
make[6]: *** [otx2_mempool_ops.o] Error 1
make[5]: *** [octeontx2] Error 2
make[4]: *** [mempool] Error 2

Fixes: 9ed8e95c ("mempool/octeontx2: optimize for L1D cache architecture")

Signed-off-by: Tao Zhu <taox.zhu@intel.com>
Signed-off-by: 0-day Robot <robot@bytheb.org>