net/mlx5: fix 32-bit build
This is to fix the error:
  ```
  drivers/net/mlx5/mlx5_defs.h:14:26: error: format '%lx' expects argument
  of type 'long unsigned int', but argument 5 has type 'off_t {aka long
  long int}' [-Werror=format=]
   #define MLX5_DRIVER_NAME "net_mlx5"
                            ^
  RTE_SDK/i686-native-linuxapp-gcc/include/rte_common.h:642:27:
  note: in definition of macro 'RTE_FMT'
   #define RTE_FMT(fmt, ...) fmt "%.0s", __VA_ARGS__ ""
                             ^~~
  RTE_SDK/drivers/net/mlx5/mlx5_utils.h:79:11: note: in expansion
  of macro 'MLX5_DRIVER_NAME'
     RTE_FMT(MLX5_DRIVER_NAME ": " \
             ^~~~~~~~~~~~~~~~
  RTE_SDK/drivers/net/mlx5/mlx5_utils.h:101:2: note: in expansion
  of macro 'PMD_DRV_LOG___'
    PMD_DRV_LOG___(level, __VA_ARGS__)
    ^~~~~~~~~~~~~~
  RTE_SDK/drivers/net/mlx5/mlx5_utils.h:103:2: note: in expansion
  of macro 'PMD_DRV_LOG__'
    PMD_DRV_LOG__(level, s "\n", __VA_ARGS__)
    ^~~~~~~~~~~~~
  RTE_SDK/drivers/net/mlx5/mlx5_utils.h:109:2: note: in expansion
  of macro 'PMD_DRV_LOG_'
    PMD_DRV_LOG_(level, \
    ^~~~~~~~~~~~
  RTE_SDK/drivers/net/mlx5/mlx5_txq.c:569:3: note: in expansion of
  macro 'DRV_LOG'
     DRV_LOG(DEBUG, "port %u: uar_mmap_offset 0x%lx",
     ^~~~~~~
  RTE_SDK/drivers/net/mlx5/mlx5_txq.c:569:48: note: format string
  is defined here
     DRV_LOG(DEBUG, "port %u: uar_mmap_offset 0x%lx"
                                                ~~^
                                                %llx
  ```
Which reproduces with gcc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0.

Fixes: 6bf10ab69be0 ("net/mlx5: support 32-bit systems")
Cc: motih@mellanox.com
Cc: stable@dpdk.org

Signed-off-by: Ali Alnubani <alialnu@mellanox.com>
Signed-off-by: 0-day Robot <robot@bytheb.org>