net/mlx5: fix 32b compilation
32b Compilation output the below error:

drivers/net/mlx5/mlx5_txq.c: In function 'mlx5_txq_ibv_new':
error: format '%lx' expects argument of type 'long unsigned int', but
argument 8 has type 'off_t' [-Werror=format=]
  DRV_LOG(DEBUG, "port %u: uar_mmap_offset 0x%lx",
  ^

Fixes: 6bf10ab69be0 ("net/mlx5: support 32-bit systems")
Cc: stable@dpdk.org

Signed-off-by: Shahaf Shuler <shahafs@mellanox.com>
Signed-off-by: 0-day Robot <robot@bytheb.org>