net/bnx2x: fix the meson compile issue
The definition is conflicting with that of the compiler, as show the
following error: ../drivers/net/bnx2x/bnx2x_osal.h:27:17: error:
conflicting types for ‘uint64_t’ #define __le64  uint64_t ^~~~ In file
included from /usr/include/stdint.h:37, from
/usr/lib/gcc/aarch64-linux-gnu/8/include/stdint.h:9, from
../lib/librte_eal/common/include/arch/arm/rte_byteorder.h:16, from
../drivers/net/bnx2x/bnx2x.h:17, from ../drivers/net/bnx2x/bnx2x_rxtx.c:8:
/usr/include/aarch64-linux-gnu/bits/stdint-uintn.h:27:20: note: previous
declaration of ‘uint64_t’ was here
typedef __uint64_t uint64_t;

The fix is to remove the duplicate definition.

Fixes: 38dff79ba736 ("net/bnx2x: update HSI")
Cc: stable@dpdk.org

Signed-off-by: Gavin Hu <gavin.hu@arm.com>
Signed-off-by: 0-day Robot <robot@bytheb.org>