net/bnx2x: fix meson build failure
Use kernel headers for __le* types to avoid potential conflicts
resulting in redefinition errors for Linux build environments.
Add check for FreeBSD execution environments.

Without this fix, aarch64 builds can fail with error [1] below.

[1]
In file included from ../drivers/net/bnx2x/bnx2x.h:22,
                 from ../drivers/net/bnx2x/bnx2x_ethdev.c:8:
../drivers/net/bnx2x/bnx2x_osal.h:27:17: error: conflicting types for
‘uint64_t’
 #define __le64  uint64_t
               ^~~~~~~~
In file included from /usr/include/stdint.h:37,
                 from
/usr/lib/gcc/aarch64-linux-gnu/8/include/stdint.h:9,
                 from
../lib/librte_eal/common/include/arch/arm/rte_byteorder.h:16,
                 from ../drivers/net/bnx2x/bnx2x.h:17,
                 from ../drivers/net/bnx2x/bnx2x_ethdev.c:8:
/usr/include/aarch64-linux-gnu/bits/stdint-uintn.h:27:20: note: previous
declaration of ‘uint64_t’ was here
 typedef __uint64_t uint64_t;
                    ^~~~~~~~

Fixes: 38dff79ba736 ("net/bnx2x: update HSI")

v2:
  Use RTE_EXEC_ENV_FREEBSD in place of __FreeBSD__

Signed-off-by: Rasesh Mody <rmody@marvell.com>
Tested-by: Dharmik Thakkar <dharmik.thakkar@arm.com>
Tested-by: Gavin Hu <gavin.hu@arm.com>
Signed-off-by: 0-day Robot <robot@bytheb.org>