net/mlx5: fix build with strict alignment enabled
This patch converts some of the casts to unaligned integer types.

This fixes the following error, which is seen on x86, with
gcc 7.4.0:

drivers/net/mlx5/mlx5_rxtx.c: In function ‘mlx5_tx_dseg_iptr’:
drivers/net/mlx5/mlx5_rxtx.c:2740:9: error: passing argument 1 of
‘memcpy’ makes pointer from integer without a cast
[-Werror=int-conversion]
  memcpy(dst, src, len);
         ^~~

The memcpy call is replaced with 2 copies of uint32 for better
performance on ARM.

Fixes: 18a1c20044c0 ("net/mlx5: implement Tx burst template")

Reported-by: Jeremy Plsek <jplsek@iol.unh.edu>
Signed-off-by: Ali Alnubani <alialnu@mellanox.com>
Signed-off-by: 0-day Robot <robot@bytheb.org>