mempool: remove inline functions from export list
The code didn't compile when using exported mempool functions under windows.

compilation error logs:
rte_mempool_exports.def : error LNK2001:
unresolved external symbol rte_mempool_cache_flush
rte_mempool_exports.def : error LNK2001:
unresolved external symbol rte_mempool_default_cache
rte_mempool_exports.def : error LNK2001:
unresolved external symbol rte_mempool_generic_get
rte_mempool_exports.def : error LNK2001:
unresolved external symbol rte_mempool_generic_put
lib\librte_mempool.dll.a : fatal error LNK1120: 4 unresolved externals
clang: error: linker command failed with exit code 1120 (use -v to see invocation)
[77/77] Linking target drivers/librte_bus_pci-0.200.2.dll.
ninja: build stopped: subcommand failed.

The cause was that there were some inline functions that were included
in the export list.
To solve this the functions were removed from rte_mempool_version.map
export list which are implemented in the header and shouldn't be exported.

Fixes: 4b5062755aa74517ed1d7bd ("mempool: allow user-owned cache")
Fixes: 656f2d3ede96902202a1a5f ("mempool: deprecate specific get and put functions")
Cc: stable@dpdk.org

Signed-off-by: Fady Bader <fady@mellanox.com>
Signed-off-by: 0-day Robot <robot@bytheb.org>